<?php

/**
 * @file
 * Contains budget.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function budget_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the budget module.
    case 'help.page.budget':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Science Meetup') . '</p>';
      return $output;

    default:
  }
}
